# build for jvm using uber-jar
#quarkus.package.type=uber-jar
FROM openjdk:17-alpine
COPY build/*.jar /home/code-with-quarkus.jar
RUN chmod 775 /home
WORKDIR /home/
EXPOSE 8080
CMD ["java", "-jar", "code-with-quarkus.jar"]
