apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: <<change_me>>
      server: <<change_me>>
    name: <<change_me>>
contexts:
  - context:
      cluster: <<change_me>>
      user: <<change_me>>
    name: <<change_me>>
current-context: <<change_me>>
kind: Config
preferences: { }
users:
  - name: <<change_me>>
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - --region
          - us-east-1
          - eks
          - get-token
          - --cluster-name
          - <<change_me>>
        command: aws