---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-06-01 - 12:38:26 +0000
  labels:
    app.kubernetes.io/part-of: code-with-quarkus-app
    app.kubernetes.io/name: code-with-quarkus-srv
    app.kubernetes.io/version: 1.1.0
  name: code-with-quarkus-srv
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-06-01 - 12:38:26 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: code-with-quarkus-srv
    app.kubernetes.io/part-of: code-with-quarkus-app
    app.kubernetes.io/version: 1.1.0
  name: code-with-quarkus-srv
spec:
  ports:
    - name: http
      nodePort: 32319
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: code-with-quarkus-srv
    app.kubernetes.io/part-of: code-with-quarkus-app
    app.kubernetes.io/version: 1.1.0
  type: NodePort
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: code-with-quarkus-srv-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: code-with-quarkus-srv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: code-with-quarkus-srv-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    name: code-with-quarkus-srv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-06-01 - 12:38:26 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/part-of: code-with-quarkus-app
    app.kubernetes.io/name: code-with-quarkus-srv
    app.kubernetes.io/version: 1.1.0
  name: code-with-quarkus-srv
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/part-of: code-with-quarkus-app
      app.kubernetes.io/name: code-with-quarkus-srv
      app.kubernetes.io/version: 1.1.0
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-06-01 - 12:38:26 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/part-of: code-with-quarkus-app
        app.kubernetes.io/name: code-with-quarkus-srv
        app.kubernetes.io/version: 1.1.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: garystafford/code-with-quarkus-srv:1.1.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: code-with-quarkus-srv
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: code-with-quarkus-srv
